name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy React App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: react-app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('react-app/package-lock.json') }}
      - name: Install dependencies
        run: |
          cd react-app
          npm install
      - name: Build
        run: |
          cd react-app
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./react-app/dist

  test:
    name: Run Playwright Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps chromium
      - name: Run tests
        run: |
          npm test
